services:
  gateway:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      - CALCULUS_SERVICE_URL=http://calculus:8001
      - DATABASE_URL=postgresql://user:password@postgres:5432/expressions_db
    networks:
      - math-network
    depends_on:
      calculus:
        condition: service_started  # Изменено с service_healthy
      postgres:
        condition: service_healthy

  calculus:
    build: ./calculus
    container_name: calculus-service
    ports:
      - "8001:8001"
    networks:
      - math-network
    healthcheck:  # Добавляем healthcheck для calculus
      test: ["CMD", "python", "-c", "import requests; r = requests.get('http://localhost:8001/health', timeout=2); exit(0) if r.status_code == 200 else exit(1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=expressions_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - math-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d expressions_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: ./web
    container_name: web-ui
    ports:
      - "8080:8000"
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - gateway
    networks:
      - math-network

networks:
  math-network:
    driver: bridge

volumes:
  postgres_data: